version: 0.2
phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      # install aws cli see https://github.com/anigeo/docker-awscli/blob/master/Dockerfile
      - mkdir -p /aws
      - apk -Uuv add groff less python py-pip
      - pip install awscli
      - apk --purge -v del py-pip
      - rm /var/cache/apk/*
      # build the docker image
      - docker build -t whatsnext-app -f Dockerfile.app .
  build:
    commands:
      # configure the project
      - echo "export const YOUTUBE_API_KEY = \"$YOUTUBE_DATA_API_KEY\";" > whatsnext/src/app/keys.ts
      - echo "export const AUTH_CLIENT_ID = \"$AUTH_CLIENT_ID\";" >> whatsnext/src/app/keys.ts
      - echo "export const AUTH_CLIENT_SECRET = \"$AUTH_CLIENT_SECRET\";" >> whatsnext/src/app/keys.ts
      # build it
      - docker run -v$(pwd):/home/node/app whatsnext-app npm install
      - docker run -v$(pwd):/home/node/app whatsnext-app ng build
      # Upload to s3
      - aws s3 rm s3://whatsnext-app --recursive
      - aws s3 cp --acl public-read --recursive whatsnext/dist/whatsnext/ s3://whatsnext-app
